// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOlqC7sGiit9ntIO7KPqtminlUV7UUY7w',
    appId: '1:1042960012220:web:7cbbabcb9cca87435f51b9',
    messagingSenderId: '1042960012220',
    projectId: 'the-beattie-chanel-group',
    authDomain: 'the-beattie-chanel-group.firebaseapp.com',
    databaseURL: 'https://the-beattie-chanel-group-default-rtdb.firebaseio.com',
    storageBucket: 'the-beattie-chanel-group.appspot.com',
    measurementId: 'G-HW6YVK219W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzPB1nLfYHXJhzX73MdgFEgBvCPH3FHwA',
    appId: '1:1042960012220:android:6821b678b3c04cb55f51b9',
    messagingSenderId: '1042960012220',
    projectId: 'the-beattie-chanel-group',
    databaseURL: 'https://the-beattie-chanel-group-default-rtdb.firebaseio.com',
    storageBucket: 'the-beattie-chanel-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIvsy6gYDvgpdBkw7tCU5MlFLKQdhwFe8',
    appId: '1:1042960012220:ios:de7c5660e4ef07cb5f51b9',
    messagingSenderId: '1042960012220',
    projectId: 'the-beattie-chanel-group',
    databaseURL: 'https://the-beattie-chanel-group-default-rtdb.firebaseio.com',
    storageBucket: 'the-beattie-chanel-group.appspot.com',
    androidClientId: '1042960012220-4ga3tg74onfgr1o6g0v8plgi49p5g7ts.apps.googleusercontent.com',
    iosClientId: '1042960012220-v0s61ib3dv5cbfhuacuffmb07cqv85ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBeattieChanelGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIvsy6gYDvgpdBkw7tCU5MlFLKQdhwFe8',
    appId: '1:1042960012220:ios:de7c5660e4ef07cb5f51b9',
    messagingSenderId: '1042960012220',
    projectId: 'the-beattie-chanel-group',
    databaseURL: 'https://the-beattie-chanel-group-default-rtdb.firebaseio.com',
    storageBucket: 'the-beattie-chanel-group.appspot.com',
    androidClientId: '1042960012220-4ga3tg74onfgr1o6g0v8plgi49p5g7ts.apps.googleusercontent.com',
    iosClientId: '1042960012220-v0s61ib3dv5cbfhuacuffmb07cqv85ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBeattieChanelGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOlqC7sGiit9ntIO7KPqtminlUV7UUY7w',
    appId: '1:1042960012220:web:94abdbb182de6be55f51b9',
    messagingSenderId: '1042960012220',
    projectId: 'the-beattie-chanel-group',
    authDomain: 'the-beattie-chanel-group.firebaseapp.com',
    databaseURL: 'https://the-beattie-chanel-group-default-rtdb.firebaseio.com',
    storageBucket: 'the-beattie-chanel-group.appspot.com',
    measurementId: 'G-N4W96T2TEL',
  );

}